"""
Portfolio & Risk Management Agent.
Calculates Expected Value, Kelly Sizing, and enforces Global Kill-Switches.
Strictly decoupled from prediction logic; focuses purely on survival mathematics.
"""

from schemas.models import SynthesizedDecision, RiskDecision, PortfolioState
from config import config

class RiskManager:
    """Gatekeeper for all trade proposals before they hit the Execution layer."""
    
    def __init__(self):
        self.slippage_pct = config.ASSUMED_SLIPPAGE_PCT
        self.fee_pct = config.ASSUMED_FEE_PCT
        self.base_kelly_fraction = config.BASE_KELLY_FRACTION
        self.drawdown_limit = config.GLOBAL_DRAWDOWN_LIMIT_PCT
        self.daily_loss_limit = config.MAX_DAILY_LOSS_PCT
        self.max_exposure_per_trade = config.MAX_RISK_PER_TRADE_PCT

    def evaluate_decision(
        self, 
        decision: SynthesizedDecision, 
        portfolio: PortfolioState,
        expected_upside_pct: float,
        expected_downside_pct: float
    ) -> RiskDecision:
        
        # 0. Validate percentage domains explicitly
        if expected_upside_pct <= 0 or expected_downside_pct <= 0:
            return self._reject(decision, "INVALID EDGE: expected_upside and expected_downside must be strictly > 0.")
            
        # 1. Check Global Kill-switches
        if portfolio.current_drawdown_pct >= self.drawdown_limit:
            return self._reject(decision, f"GLOBAL KILL-SWITCH: Portfolio max drawdown ({portfolio.current_drawdown_pct*100:.2f}%) exceeded.")
            
        if portfolio.daily_realized_pnl_pct <= -self.daily_loss_limit:
            return self._reject(decision, f"DAILY LOSS LIMIT: Maximum daily loss ({self.daily_loss_limit*100:.2f}%) exceeded.")

        # 2. Hard "No Trade" states generated by Strategy Disagreement
        if decision.final_decision in ["no_trade", "hold"]:
            return self._reject(decision, "Strategy Coordinator enforced No-Trade/Hold state. No capital allocated.")

        # 3. Calculate Net EV
        p_win = decision.synthesized_probability
        p_loss = 1.0 - p_win
        
        # Factor in realistic execution drag
        drag_pct = self.slippage_pct + self.fee_pct
        expected_profit = expected_upside_pct - drag_pct
        expected_loss = expected_downside_pct + drag_pct
        
        net_ev_pct = (p_win * expected_profit) - (p_loss * expected_loss)
        if net_ev_pct <= 0:
            return self._reject(decision, f"NEGATIVE EV: Net Expected Value is {net_ev_pct:.4f}%. Trade aborted.")

        # 4. Calculate Kelly Sizing
        win_loss_ratio = expected_profit / expected_loss
        raw_kelly = p_win - (p_loss / win_loss_ratio)
        
        if raw_kelly <= 0:
            return self._reject(decision, f"NEGATIVE KELLY: Raw Kelly fraction is {raw_kelly:.4f}. Trade aborted.")
            
        # 5. Apply Fractional Kelly and Uncertainty Penalty
        uncertainty_penalty = decision.uncertainty_score
        penalty_factor = 1.0 - uncertainty_penalty
        
        kelly_fraction_suggested = raw_kelly * self.base_kelly_fraction * penalty_factor
        
        # YOLO MODE RULE: Max Position Size 15% of total account equity
        PLAYBOOK_MAX_POS_PCT = 0.15
        if kelly_fraction_suggested > PLAYBOOK_MAX_POS_PCT:
            kelly_fraction_suggested = PLAYBOOK_MAX_POS_PCT
            
        if kelly_fraction_suggested <= 0.005:  # Ignore micro-trades (< 0.5% allocation)
            return self._reject(decision, f"INSUFFICIENT EDGE: Uncertainty heavily penalized size to {kelly_fraction_suggested:.4f}.")
            
        # 6. Capital Allocation & Total Exposure Check (YOLO MODE RULE: Max 80% Total Exposure)
        total_value_at_risk = sum([pos_value for pos_value in portfolio.open_positions.values()]) # This is illustrative; assuming simple dollar value for MVP
        # In a real system we'd calculate Notional. For MVP, we'll check cash levels.
        
        # Total Exposure Limit: 80% of total equity
        PLAYBOOK_TOTAL_EXPOSURE_CAP = 0.80
        current_exposure_pct = 1.0 - (portfolio.available_cash_usd / portfolio.total_capital_usd)
        
        if (current_exposure_pct + kelly_fraction_suggested) > PLAYBOOK_TOTAL_EXPOSURE_CAP:
             # Calculate remaining room
             available_room_pct = max(0.0, PLAYBOOK_TOTAL_EXPOSURE_CAP - current_exposure_pct)
             if available_room_pct < 0.01:
                 return self._reject(decision, f"PLAYBOOK EXPOSURE LIMIT: Total exposure would exceed {PLAYBOOK_TOTAL_EXPOSURE_CAP*100}%.")
             kelly_fraction_suggested = available_room_pct


        final_capital_usd = portfolio.total_capital_usd * kelly_fraction_suggested
        
        if final_capital_usd > portfolio.available_cash_usd:
            final_capital_usd = portfolio.available_cash_usd 
            
        return RiskDecision(
            asset=decision.asset,
            approved=True,
            net_expected_value_pct=net_ev_pct,
            kelly_fraction_suggested=kelly_fraction_suggested,
            uncertainty_penalty_applied=uncertainty_penalty,
            final_capital_allocation_usd=final_capital_usd,
            market_regime=decision.market_regime
        )

    def _reject(self, decision: SynthesizedDecision, reason: str) -> RiskDecision:
        return RiskDecision(
            asset=decision.asset,
            approved=False,
            net_expected_value_pct=0.0,
            kelly_fraction_suggested=0.0,
            uncertainty_penalty_applied=decision.uncertainty_score,
            final_capital_allocation_usd=0.0,
            market_regime=decision.market_regime,
            rejection_reason=reason
        )
