"""
Pydantic Schemas for Inter-Agent Communication and State Management.
Enforces strict type safety and probabilistic rules across the system.
"""

from typing import Literal, Optional, List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone

class AgentProbability(BaseModel):
    """Represents a strategy agent's pure probabilistic edge."""
    probability_of_success: float = Field(..., ge=0.0, le=1.0, description="P(Win)")
    expected_upside_pct: float = Field(..., description="Expected take profit distance in decimal (e.g., 0.05)")
    expected_downside_pct: float = Field(..., description="Expected stop loss distance in decimal (e.g., 0.02)")

class MarketRegimeClassification(BaseModel):
    """Explicit market classification for strategy weighting."""
    regime: Literal["bull_volatile", "bull_quiet", "bear_volatile", "bear_quiet", "ranging_choppy"]
    confidence: float = Field(..., ge=0.0, le=1.0)
    volatility_index: float
    key_drivers: List[str]
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class RAGContext(BaseModel):
    """Retrieved knowledge context from the Vector DB."""
    query: str
    top_k_chunks: List[str]
    source_documents: List[str]
    retrieval_confidence: float = Field(..., ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class PortfolioState(BaseModel):
    """Real-time portfolio state and constraints."""
    total_capital_usd: float
    available_cash_usd: float
    open_positions: Dict[str, Any]  # e.g., {"BTC-USD": {"usd_value": 5000, "unrealized_pnl_pct": 0.05}}
    daily_realized_pnl_pct: float
    current_drawdown_pct: float
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class CalibrationMetrics(BaseModel):
    """Memory & Learning calibration tracking for Strategy Agents."""
    strategy_name: str
    rolling_win_rate: float = Field(..., ge=0.0, le=1.0)
    brier_score: float = Field(..., ge=0.0, le=1.0, description="0 is perfect, 1 is worst")
    reliability_haircut: float = Field(..., ge=0.0, le=1.0, description="Penalty applied to future probs")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class TradeProposal(BaseModel):
    """The formal trade proposal submitted by a Strategy Agent."""
    strategy_name: str
    asset: str
    decision: Literal["long", "short", "hold"]
    probabilities: AgentProbability
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Agent's raw algorithmic confidence")
    market_regime: MarketRegimeClassification
    reasoning: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class SynthesizedDecision(BaseModel):
    """The unified decision generated by the Strategy Coordinator after debating proposals."""
    asset: str
    final_decision: Literal["long", "short", "hold", "no_trade"]
    winning_strategy: Optional[str] = None
    synthesized_probability: float = Field(..., ge=0.0, le=1.0)
    uncertainty_score: float = Field(..., ge=0.0, le=1.0, description="0.0 = total agreement, 1.0 = chaos")
    expected_value_raw: float
    market_regime: MarketRegimeClassification
    reasoning_summary: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class RiskDecision(BaseModel):
    """The final gatekeeper decision from the Portfolio/Risk Manager."""
    asset: str
    approved: bool
    net_expected_value_pct: float
    kelly_fraction_suggested: float
    uncertainty_penalty_applied: float
    final_capital_allocation_usd: float = Field(..., ge=0.0)
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    market_regime: MarketRegimeClassification
    rejection_reason: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class ExecutionReport(BaseModel):
    """The simulated outcome from the Paper Broker."""
    order_id: str
    asset: str
    action: Literal["buy", "sell"]
    requested_price: float
    fill_price: float
    quantity: float
    slippage_pct: float
    fee_usd: float
    status: Literal["filled", "partial", "rejected"]
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
