"""
End-to-End Dry Run script to verify module imports and MVP scaffolding logic.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from schemas.models import TradeProposal, AgentProbability, MarketRegimeClassification
from backtest.engine import BacktestEngine

def run_dry_run():
    print("Initializing Backtest Engine & Paper Broker...")
    engine = BacktestEngine(initial_capital=100000.0)
    
    # 1. Mock the Regime 
    regime = MarketRegimeClassification(
        regime="bull_volatile", confidence=0.85, volatility_index=28.0, key_drivers=["CPI beat"]
    )
    
    # 2. Mock a Trade Proposal generated by an Agent
    proposal = TradeProposal(
        strategy_name="VolatilityBreakout",
        asset="NVDA",
        decision="long",
        probabilities=AgentProbability(
            probability_of_success=0.65, # 65% win rate
            expected_upside_pct=0.08,    # 8% upside
            expected_downside_pct=0.03   # 3% downside (~2.6R)
        ),
        confidence_score=0.2, # Representing a 0.2 Uncertainty Penalty at the Coordinator level
        market_regime=regime,
        reasoning="Explosive breakout context with high volume backing."
    )
    
    print("\n[1] Submitting Trade Proposal to Strategy Coordinator & Risk Manager...")
    result = engine.process_proposal(proposal, current_price=950.00)
    
    # Check if result is a rejection (RiskDecision without 'fill_price') or an ExecutionReport
    if hasattr(result, 'rejection_reason') and getattr(result, 'rejection_reason') is not None:
        print(f"\n[X] Trade Rejected via Risk Manager: {result.rejection_reason}")
    else:
        print(f"\n[2] Trade Approved! Routed through Paper Broker execution physics...")
        print(f"Fill Price: ${result.fill_price:.2f}")
        print(f"Quantity Purchased: {result.quantity:.4f} shares")
        print(f"Simulated Volatility-Scaled Slippage: {result.slippage_pct * 100:.4f}%")
        print(f"Fee Deducted: ${result.fee_usd:.2f}")
        
    print("\n[3] Portfolio State Snapshot")
    print(f"Liquid Cash Remaining: ${engine.portfolio.available_cash_usd:.2f}")
    print(f"Total Portfolio NAV: ${engine.portfolio.total_capital_usd:.2f}")

if __name__ == "__main__":
    run_dry_run()
